apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: gatekeeper-lib
  namespace: fleet-default
spec:
  branch: master
  insecureSkipTLSVerify: false
  paths:
  - /lib/psp/allow-pe/samples/
  - /lib/psp/apparmor/samples/
  - /lib/psp/capabilities/samples/
  - /lib/psp/fv-drivers/samples/
  - /lib/psp/sysctls/samples/
  - /lib/psp/fsgroup/samples/
  - /lib/psp/host-filesystem/samples/
  - /lib/psp/host-namespaces/samples/
  - /lib/psp/host-net-ports/samples/
  - /lib/psp/priv-ctrs/samples/
  - /lib/psp/proc-mount/samples/
  - /lib/psp/ro-root-fs/samples/
  - /lib/psp/seccomp/samples/
  - /lib/psp/selinux/samples/
  - /lib/psp/users/samples/
  - /lib/psp/volumes/samples/
  repo: https://github.com/shpwrck/gatekeeper-library
  targets:
  - clusterSelector: {}
type: fleet.cattle.io.gitrepo
